version: '3.9'
services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 16000:16000
      - 26000:26000
    volumes:
      - isos:/app/iso
      - config:/app/data
    environment:
      - AUTO_START_PXE=true

volumes:
  isos:
    external:
      name: iventoy-isos
  config:
    external:
      name: iventoy-config

networks:
  bridge:
    external:
      name: bridge
